env:
  CIRRUS_CLONE_DEPTH: "1"
  GITHUB_TOKEN: "ENCRYPTED[75db4a3a95cd4858ff61d5de8bbab14abc02b739c03c6fbc54ee53228e8afe3467f5d5e9f1094532325321379d1863c9]"

arm64_task:
  name: ARM64 build
  timeout_in: 120m
  container:
    image: alpine:latest
    cpu: 8
    memory: 20G
  setup_env_script:
    - apk add gcc g++ texinfo make curl bash ninja bison flex git cmake clang lld mpfr-dev mpc1-dev llvm clang python3
  build_script:
    - env bash ci.sh --arm64

arm_task:
  name: ARM build
  timeout_in: 120m
  container:
    image: alpine:latest
    cpu: 8
    memory: 20G
  setup_env_script:
    - apk add gcc g++ texinfo make curl bash ninja bison flex git cmake clang lld mpfr-dev mpc1-dev llvm clang python3
  build_script:
    - env bash ci.sh --arm
